<?php

declare(strict_types=1);

namespace Symfony\UX\Typesense;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class TypesenseBundle extends Bundle
{

    public function build(ContainerBuilder $container)
    {
        parent::build($container);
        $this->container = $container;
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $this->entityManager = $this->container->get("doctrine.orm.entity_manager");
    }
}